### ISSUE TITLE
Resume Print View Has Scrollbar in Windows 8.1, Chrome 51.0.2704.103

### ISSUE THREAD

**Issue by rye** [rye/old-krye.io#27]
[yikes.pdf](https://github.com/rye/krye.io/files/412168/yikes.pdf) courtesy of @cg505.  Research Windows scrollbar disabling.

**Comment by rye** [comment]
This can probably be rectified by setting `overflow-y: hidden;` on body, however I do concede that it would be much better if there was _no reason_ for body to require a scroll-bar in the first place.

**Comment by rye** [comment]
Except not.  Better to do this instead:

``` css
::-webkit-scrollbar {
  width: 0px; /* remove scrollbar space */
  background: transparent; /* optional: just make scrollbar invisible */
}
```
